image: node:latest

cache:
  paths:
    - node_modules/

before_script:
  - npm ci

build:
  stage: build
  script:
    - npm run build

lint:
  stage: test
  script:
    - npm run lint

deploy_dev:
  stage: deploy
  environment:
    name: dev
    url: https://carrus-dev.web.app
  only:
    - master
  script:
    - npm install -g firebase-tools
    - npm --prefix functions ci
    - npm run deploy:dev:ci